apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: volt-api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app.kubernetes.io/name: volt-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: volt-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}-api:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
